apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-booking-config
data:
  PORT: "5000"                              # ตัวเลขต้องใส่ quote ด้วย เพราะ ConfigMap เก็บเป็น string เสมอ
  FRONTEND_URL: "https://hotel.phumitada.com"
